### ISSUE TITLE
Wrong units on x-axis of overview graph

### ISSUE THREAD

**Issue by IanMayo** [debrief/mda#1]
The overview graph is meant to have time on the x-axis:

![image](https://cloud.githubusercontent.com/assets/1108513/20262194/14711678-aa59-11e6-8072-316d5b2a15e4.png)

The data-ranges are configured correctly, but it's showing a row counter instead of time.

**Comment by gwenaeldelaleux** [comment]
[OwnshipZig2.xlsx](https://github.com/debrief/mda/files/589192/OwnshipZig2.xlsx)

**Comment by IanMayo** [comment]
Resolved in this version: https://github.com/debrief/mda/commit/27237002889b5be37b71225a76612643a6b5f188
