### ISSUE TITLE
Switch origin of window comparison

### ISSUE THREAD

**Issue by IanMayo** [debrief/mda#2]
We do a high level test of whether a manoeuvre has been conducted by seeing if two windowed moving average differ by more than 5 degrees.

We do this test at each time step.  We currently compare the window centred at this time step with the following window.

We should test the window that finishes at this time step with the window that starts at this time step.

![image](https://cloud.githubusercontent.com/assets/1108513/20262806/cb5c8d16-aa5b-11e6-999c-ad082fc54cdc.png)

So, in the above diagram at time t4 we compare w1 with w5.  But, we should defer tests until t8, when we compare w1 with w5, then at t10 we compare w2 with w6, and so on.

**Update:** actually, this may have been resolved in version 3.  Gwen said: 
*Formula for delta as been changed as followed : delta(t) = average(t+W/2) - average(t-W/2)  ; you could understand better on the Excel file.*

**Comment by GDXFR** [comment]
This issue is already corrected on commit 2723700.
