### ISSUE TITLE
Display legs on "Window" graph

### ISSUE THREAD

**Issue by IanMayo** [debrief/mda#3]
We need to consider exactly when the algorithm thinks the turn started.

The "Window" graph is the best place for this.

So, we need to see some indication of the leg change on the graph. This could be the Leg counter (column D), or the on/off indicators (columns P & Q)

**Comment by IanMayo** [comment]
Aah, we have a problem.

Since we're using 0..360 to indicate whether there is a leg or not, the y-axis of the window graph is always scaled 0..360.  That prevents it auto-scaling to show the detail of the course data.

![image](https://cloud.githubusercontent.com/assets/1108513/20270406/d7270072-aa7e-11e6-94b5-920b3d7f86bf.png)

I can't immediately think of a solution, since we're already using the secondary y-axis to show the delta error.  I guess we could show the legs using 0 or 5.0 on the secondary axis?  0 or 5 won't fill the range, but we'll still have an indicator.

**Comment by GDXFR** [comment]
The legs axis have been changed to secondary axis (same than Delta). Is it convenient for you?

**Comment by IanMayo** [comment]
Ok.  Plotting legs on secondary axis, and have fixed axes to 0..5 range.  Hmm, actually 10 or 20 would be a better limit, sine we may end up using a threshold of more than 5 degs. Will have a play

**Comment by IanMayo** [comment]
Ok, sorted.
