### ISSUE TITLE
Introduce other trial data

### ISSUE THREAD

**Issue by IanMayo** [debrief/mda#6]
The spreadsheet contains the first of three data-sets we hold (OwnshipTrialOne.xslx).

I'd like you to include the other data-sets, please.  Then we can add a UI feature to let the analyst move between the three data-sets.

I guess we have two strategies for including the data:
* one worksheet per dataset, and use a fancy trick to change which data is shown on our working sheet
* all the datasets on one worksheet, side-by-side. We can then use the *column index* value in an *offset* function to determine which dataset to use.

[trial_data.zip](https://github.com/debrief/mda/files/589914/trial_data.zip)

**Comment by GDXFR** [comment]
I think it would be a good idea to enable to choose different data set ; however all raw data should be the same.

What about generating several csv or excel file with Elapsed secs   Counter Speed (m/s) Heading (deg)
 titles and import them trough a selector on the main page?

**Comment by IanMayo** [comment]
For this early stage, when we're "experimenting" with the algorithms, it would be easier to have the data all in a single file - with us able to switch between them (hopefully using a radio button).

We can re-organise the data into those columns.

**Comment by IanMayo** [comment]
@gwenaeldelaleux - could you double-check the time data for the new datasets?  

I'm suspicious about the "quantisation" in Dataset 2.   Aah, hold on - it's because we only have one decimal place in the heading column.  I bet that impacts our algorithm.  But, I think we have to ensure our algorithm(s) can handle this type of data.

**Comment by IanMayo** [comment]
Aah. @gwenaeldelaleux  - separate issue.

I guess your first version may just be to prove the viability of the "multiple datasets - one worksheet" method.  But, the heading data doesn't seem to match the test data-files.   Dataset 3 is the same as Dataset 1, and Dataset 2 doesn't seem to match the contents of the spreadsheet (where the course starts at 192.87)

**Comment by GDXFR** [comment]
Yes, I added +180deg in order to avoid negatives degrees.

**Comment by IanMayo** [comment]
@gwenaeldelaleux  - Oooh, I wish I'd thought of this :-)  I spend half my life making that correction.

**Comment by GDXFR** [comment]
Three trial have been integreted.

**Comment by IanMayo** [comment]
I'm pretty sure we're not including **OwnshipTrialTwo**

Here are the values in the spreadsheet (it's the CoG that we need):
![trialtwo](https://cloud.githubusercontent.com/assets/1108513/20350086/390a060e-ac05-11e6-9b64-eb6ffc08074f.png)

But, here is the raw data:
![rawdata](https://cloud.githubusercontent.com/assets/1108513/20350098/4d7264d8-ac05-11e6-8c78-0b2de2f1dd42.png)

**Comment by IanMayo** [comment]
Ok, I've seen the new file.  The data is correctly imported. Thanks :-)
