### ISSUE TITLE
Display Delta 2 legs

### ISSUE THREAD

**Issue by IanMayo** [debrief/mda#7]
The spreadsheet has columns to indicate the current leg, and a calculated value of height for that leg.

I wish to display the results of the new Delta2 calculation on the Window graph.

I believe we'll need two new calculated columns in order to display this.

So, please create a new _Leg 2_ column that increments a counter if the _Delta2_ indicates we have started (or finished) a turn. This logic can be the same as the "Leg" column.

Aah, we also need a new _Leg 2_ dataset on the Window graph (we've already got *Delta 2* on there).

**Comment by GDXFR** [comment]
Leg2 added on the Window graph in orange: results seem a way better!

**Comment by IanMayo** [comment]
Cool - could you Push/Sync it?

**Comment by IanMayo** [comment]
Looking great:
![image](https://cloud.githubusercontent.com/assets/1108513/20306093/9dcd8654-ab30-11e6-9fb3-396546d8b745.png)
