### ISSUE TITLE
Investigate moving average calculation

### ISSUE THREAD

**Issue by IanMayo** [debrief/mda#8]
The legs we plot for the moving average window appear to show too early on the graph.  In the screenshot below the red turn starts at around 550 and finishes at around 760.

![image](https://cloud.githubusercontent.com/assets/1108513/20307458/72e97edc-ab37-11e6-8538-f92a00bd13a6.png)

Could you double-check that the algorithm correctly compares the moving average that finishes at this time step with the moving average that starts at this time step?

**Comment by GDXFR** [comment]
![image](https://cloud.githubusercontent.com/assets/23452311/20309371/a7c4258a-ab82-11e6-9f83-d5f1cb7370b5.png)

The Legs calculation have been modify to be calcultated based on Delta and not Next Delta (Delta compares the moving average that finishes at this time step with the moving average that starts at this time step)

**Comment by GDXFR** [comment]
![image](https://cloud.githubusercontent.com/assets/23452311/20309473/09af0224-ab83-11e6-9ee5-5d3262ef97f4.png)

Moving average depending on window size, legs calculation is different

**Comment by IanMayo** [comment]
Great work, thanks.
