### ISSUE TITLE
Consolidate how we render legs

### ISSUE THREAD

**Issue by IanMayo** [debrief/mda#9]
The overview graph currently relies on the specially formatted block of cells [1] in Columns Q:S

The window graph uses data in columns F & O [2].

[1] has the downside that it requires a _placeholder_ for each turn.  We would also have to duplicate that structure to handle the "Delta2" turns.

[2] has the downside that it requires potentially thousand more points to be plotted on the graph.

@gwenaeldelaleux - I'd like to settle on one way of doing it.  My gut feeling is that [1] offers a performance improvement.  What do you think?

**Comment by GDXFR** [comment]
In my opinion [2] is better in the way that it follows structure of the file, period by period. Then the vessel route could be also calculated period by period.

**Comment by IanMayo** [comment]
Ok. Could you switch the overview to use [2]?

(though this is a low priority task)

**Comment by IanMayo** [comment]
Aah, given the "line-chart vs scatter chart" issue at #13 , I think it may be justified to try to plot the legs using XY-values (Strategy [1]), rather than one per line.  Significantly, switching the 3 different "leg markers" to simple xy-coordinates will result in removing the need to (potentially) plot lines with 10s of 1000s of elements.  Yes, we do this for most of the other calculated fields, but it still seems to represent an efficiency.

**Comment by IanMayo** [comment]
Fixed in https://github.com/debrief/mda/commit/fdd61a5fb3bcc940747a1107ca13e5d6e0331d64
